### ISSUE TITLE
mpl2

### ISSUE THREAD

**Issue by marqh** [SciTools/nc-time-axis#23]
there is a potential bug with respect to matplotlib2 in tick locations

the version of mpl is now pinned, pending this fix

https://github.com/SciTools/nc-time-axis/blob/master/nc_time_axis/tests/unit/test_NetCDFTimeDateLocator.py#L99
https://github.com/SciTools/nc-time-axis/blob/master/nc_time_axis/tests/unit/test_NetCDFTimeDateLocator.py#L107
https://github.com/SciTools/nc-time-axis/blob/master/nc_time_axis/tests/unit/test_NetCDFTimeDateLocator.py#L111

ref #22

**Comment by QuLogic** [comment]
There are two problems. Firstly, `MaxNLocator` changed with mpl2; tests could maybe be fixed by setting classic style first. Secondly, [this code](https://github.com/SciTools/nc-time-axis/blob/master/nc_time_axis/__init__.py#L99-L100) supplies invalid `steps`; it should start at 1 and end at 10 (as specified in the [`MaxNLocator` docs](http://matplotlib.org/api/ticker_api.html#matplotlib.ticker.MaxNLocator)).

**Comment by marqh** [comment]
thanks for the tips @QuLogic
